services:
  postgres:
    image: postgres:16-alpine
    container_name: aether-postgres
    environment:
      POSTGRES_DB:  aether
      POSTGRES_USER: aether
      POSTGRES_PASSWORD: aether_local_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U aether"]
      interval: 10s
      timeout:  5s
      retries:  5
    networks:
      - aether-net

  redis:
    image:  redis:7-alpine
    container_name: aether-redis
    volumes:
      - redis-data:/data
    healthcheck: 
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: 
      - aether-net

  ollama:
    image:  ollama/ollama:latest
    container_name:  aether-ollama
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - aether-net

  open-webui: 
    image: ghcr.io/open-webui/open-webui:latest
    container_name: aether-webui
    ports:
      - "3000:8080"
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      REDIS_URL: redis://redis:6379
      WEBUI_AUTH: "true"
      ENABLE_RAG_WEB_LOADER_SSL_VERIFICATION:  "false"
    depends_on:
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
    restart: unless-stopped
    networks:
      - aether-net

volumes:
  postgres-data:
  redis-data: 
  ollama-data: 
  open-webui-data: 

networks:
  aether-net:
    driver: bridge
